version: "3.7"
services:
  import-app:
    build: D:\project\data_import\app
    container_name: import-app
    links:
      - main-app
    ports:
      - "9091:9091"
    networks:
      - database-network
    depends_on:
      - main-app
    tty: true
    volumes:
      - //d/test:/test
  main-app:
    build: main/
    container_name: main-app
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    links:
      - docker-mysql
    ports:
      - "9081:9081"
      - "9080:9080"
# outside:inside
    networks:
      - database-network
    depends_on:
      - docker-mysql
    tty: true
  docker-mysql:
    image: pitchanon/docker-mysql
    container_name: docker-mysql
    ports:
      - "6603:3306"
    networks:
      - database-network
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "db1"
    tty: true
networks:
  database-network: {}