version: "3.7"
services:
  import-app:
    build: D:\backup\workspace\data_import\app
    container_name: import-app
    links:
      - main-app
    ports:
      - "8080:9091"
    networks:
      - database-network
    depends_on:
      - main-app
    tty: true
    volumes:
      - //d/test:/test
  main-app:
    build: main/
    container_name: main-app
    links:
      - docker-mysql
      - kafka
    ports:
      - "8081:9080"
    networks:
      - database-network
    depends_on:
      - docker-mysql
      - kafka
    tty: true
  docker-mysql:
    image: pitchanon/docker-mysql
    container_name: docker-mysql
    ports:
      - "6603:3306"
    networks:
      - database-network
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "db1"
    tty: true
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2147483647
      KAFKA_CREATE_TOPICS: "registerEmail:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - database-network
    tty: true
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - database-network
    tty: true
networks:
  database-network: {}